### PR TITLE
backslashes must be escaped on write

### PR DESCRIPTION
**Pull request by apesternikov**
according to https://docs.oracle.com/cd/E23095_01/Platform.93/ATGProgGuide/html/s0204propertiesfileformat01.html
*The backslash character must be escaped as a double backslash*

### CODE REVIEW

**Comment by apesternikov** [comment]
@magiconair could you please take a look? Thank you

**Comment by magiconair** [comment]
I'll have a look over the weekend. Want to make sure that the right tests are covered.

**Comment by apesternikov** [comment]
It was a year since the last response. Any progress in reviewing so far?
Thank you

**Comment by magiconair** [comment]
This looks good to me. Will this break any existing code or break reading existing files?

**Comment by magiconair** [comment]
Sorry for the late response

**Comment by apesternikov** [comment]
This change would not break reading existing files since it only affects writing.
Speaking of breaking existing code - it is entirely possible that code relying on this bug presence exists. I am not specifically aware of such code. According to https://pkg.go.dev/github.com/magiconair/properties?tab=importedby 223 opensource projects imports this package as of today, I am not sure how many of them are using the writing path.
If you want to make sure no existing code is affected you can probably consider releasing v2?

**Comment by apesternikov** [comment]
ping?

**Comment by magiconair** [comment]
Lets do this.

**Comment by apesternikov** [comment]
thank you!

**Pull request merged**
